---
title: "Lotka-volterra example"
date: "`r Sys.Date()`"
author: "Juho Timonen and Ben Bales"
output:
  html_document:
    number_sections: true
    toc: true
    toc_float: true
    toc_depth: 4
    highlight: pygments
    theme: cosmo
    css: "style.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load, message=FALSE}
# Requirements
require(rstan)
library(tidyverse)
require(bayesplot)
require(ggplot2)
require(loo)
require(stats)
require(posterior)
set.seed(123) # rng seed for data simulation
```

# Functions

```{r functions}

# Compute integers r_1, ..., r_n
compute_R <- function(t0, ts, h){
  n <- length(ts)
  R <- rep(0, n)
  for (i in 1:n) {
    r <- 0
    while (t0 + r*h < ts[i]) {
      r <- r + 1
    }
    R[i] <- r - 1
  }
  return(R)
}

# Compute multipliers a_1, ..., a_n
compute_A <- function(t0, ts, h, R){
  n <- length(ts)
  A <- rep(0, n)
  for (i in 1:n) {
    D_i <- ts[i] - (t0 + R[i]*h)
    A[i] <- (h - D_i)/h
  }
  return(A)
}

# Create additional Stan data related to some ODE solver methods
add_interpolation_data <- function(data_list, h){
  t0 <- data_list$t0
  ts <- data_list$ts
  R  <- compute_R(t0, ts, h)
  A  <- compute_A(t0, ts, h, R)
  data_list$STEP_SIZE <- h
  data_list$INTERP_R  <- R
  data_list$INTERP_A  <- pmax(A, 0) # rounding errors can cause A < 0
  return(data_list)
}

# Helper function
get_samples <- function(stan_fit, param){
  samples <- rstan::extract(stan_fit, pars = param)[[param]]
  return(samples)
}
```

# Generate data

```{r sim1}
# Simulation setup
theta    <- c(1.0, 2.0) # ODE params
by       <- 0.5
T_max    <- 6
N_sets   <- 1 # number of data set realizations
y0       <- c(1, 1) # initial values
sigma <- 0.5 # noise magnitude

# Compile simulation model
sm <- stan_model(file = "stan/lv_simulate.stan")

# Simulate data
th <- as.array(c(theta))
ts <- seq(by, T_max, by=by)
d1 <- list(T=length(ts), y0=y0, t0=0, ts=ts, theta=th, sigma=sigma)
f1 <- sampling(sm, data = d1, chains = 1, cores = 1, iter = N_sets, warmup=0, algorithm="Fixed_param")
y_hat <- rstan::extract(f1)$y_hat
y  <- rstan::extract(f1)$y

# Store data in a list
data_idx <- 1
dat <- list(y_hat=y_hat[data_idx,,], y=y[data_idx,,], 
            ts=ts, t0=0, T=length(ts), sigma=sigma, idx=data_idx)

```

```{r plot1}
print(dat)
```

```{r fitting}
# A function that runs the inference
run_inference <- function(model, data, ITER, CHAINS, ADAPT_DELTA){
  
  # Run sampling
  fit <- sampling(object  = model,
                  data    = data,
                  iter    = ITER,
                  chains  = CHAINS,
                  control = list(adapt_delta = ADAPT_DELTA),
                  init    = "0",
                  save_warmup=FALSE)
  
  # Extract log posterior values (not Jacobian adjusted)
  lh1 <- get_samples(fit, 'log_lik_na')
  lh2 <- get_samples(fit, 'log_lik_na_REF_')
  pr1 <- get_samples(fit, 'log_prior_na')
  pr2 <- get_samples(fit, 'log_prior_na_REF_')
  post1 <- as.vector(lh1) + as.vector(pr1)
  post2 <- as.vector(lh2) + as.vector(pr2)
  
  # PSIS
  out <- psis(post1 - post2)
  pareto_k <- out$diagnostics$pareto_k
  runtimes <- rowSums(get_elapsed_time(fit))
  
  # Return list
  return(list(pareto_k=pareto_k, runtimes=runtimes, fit=fit))
  
}
```


```{r model}
# Compile model
model <- stan_model(file = "stan/lv_rk4.stan")

# Options
ADAPT_DELTA <- 0.95
CHAINS      <- 4
ITER        <- 2000
DATA_IDX <- 1

# Load data
data <- dat
data$abs_tol_REF_  <- 1.0E-6
data$rel_tol_REF_  <- 1.0E-6
data$max_iter_REF_ <- 1.0E4

# Run with different step sizes
H <- seq(0.1, 1, by = 0.1)
L <- length(H)
for (i in 1:L) {
  step_size <- H[i]
  
  # Additional data
  new_data <- data
  new_data <- add_interpolation_data(new_data, h = step_size)
  
  # Run inference
  res <- run_inference(model, new_data, ITER, CHAINS, ADAPT_DELTA)
  print(res$pareto_k)
  print(res$runtimes)
  res$step_size <- step_size
}

```
